export const ACTION_SET_FROM = "SET_FROM";
export const ACTION_SET_TO = "SET_TO";
export const ACTION_SET_ISCITYSELECTORVISIBLE = "SET_ISCITYSELECTORVISIBLE";
export const ACTION_SET_CURSELECTINGCITY = "SET_CURSELECTINGCITY";
export const ACTION_SET_CITYDATA = "SET_CITYDATA";
export const ACTION_SET_ISLOADINGCITYDATA = "SET_ISLOADINGCITYDATA";
export const ACTION_SET_ISDATESELECTORVISIBLE = "SET_ISDATESELECTORVISIBLE";
export const ACTION_SET_HIGH_SPEED = "SET_HIGH_SPEED";
